export const initialProducts = [
  {
    id: 1,
    image: "https://via.placeholder.com/80",
    name: "Áo thun nam trắng",
    type: "Áo",
    size: "M",
    color: "Trắng",
    price: 250000,
    stock: 20,
  },
  {
    id: 2,
    image: "https://via.placeholder.com/80",
    name: "Quần jeans nữ",
    type: "Quần",
    size: "L",
    color: "Xanh",
    price: 350000,
    stock: 15,
  },
  {
    id: 3,
    image: "https://via.placeholder.com/80",
    name: "Áo khoác da đen",
    type: "Áo",
    size: "XL",
    color: "Đen",
    price: 700000,
    stock: 10,
  },
  {
    id: 4,
    image: "https://via.placeholder.com/80",
    name: "Váy hoa hồng",
    type: "Váy",
    size: "S",
    color: "Hồng",
    price: 420000,
    stock: 8,
  },
  {
    id: 5,
    image: "https://via.placeholder.com/80",
    name: "Áo sơ mi trắng",
    type: "Áo",
    size: "M",
    color: "Trắng",
    price: 300000,
    stock: 12,
  },
  {
    id: 6,
    image: "https://via.placeholder.com/80",
    name: "Quần tây nam",
    type: "Quần",
    size: "L",
    color: "Đen",
    price: 400000,
    stock: 25,
  },
  {
    id: 7,
    image: "https://via.placeholder.com/80",
    name: "Chân váy dài",
    type: "Váy",
    size: "M",
    color: "Be",
    price: 330000,
    stock: 18,
  },
  {
    id: 8,
    image: "https://via.placeholder.com/80",
    name: "Áo hoodie",
    type: "Áo",
    size: "XL",
    color: "Xám",
    price: 550000,
    stock: 10,
  },
  {
    id: 9,
    image: "https://via.placeholder.com/80",
    name: "Quần short nam",
    type: "Quần",
    size: "L",
    color: "Xanh navy",
    price: 270000,
    stock: 30,
  },
  {
    id: 10,
    image: "https://via.placeholder.com/80",
    name: "Áo len nữ",
    type: "Áo",
    size: "M",
    color: "Đỏ",
    price: 380000,
    stock: 22,
  },
  {
    id: 11,
    image: "https://via.placeholder.com/80",
    name: "Áo khoác gió",
    type: "Áo",
    size: "L",
    color: "Xanh dương",
    price: 600000,
    stock: 9,
  },
  {
    id: 12,
    image: "https://via.placeholder.com/80",
    name: "Váy công sở",
    type: "Váy",
    size: "M",
    color: "Đen",
    price: 500000,
    stock: 14,
  },
  {
    id: 13,
    image: "https://via.placeholder.com/80",
    name: "Áo polo nam",
    type: "Áo",
    size: "M",
    color: "Xanh",
    price: 320000,
    stock: 17,
  },
  {
    id: 14,
    image: "https://via.placeholder.com/80",
    name: "Quần kaki",
    type: "Quần",
    size: "L",
    color: "Be",
    price: 370000,
    stock: 16,
  },
  {
    id: 15,
    image: "https://via.placeholder.com/80",
    name: "Áo thun nữ in hình",
    type: "Áo",
    size: "S",
    color: "Trắng",
    price: 280000,
    stock: 19,
  },
  {
    id: 16,
    image: "https://via.placeholder.com/80",
    name: "Áo sơ mi caro",
    type: "Áo",
    size: "M",
    color: "Đỏ",
    price: 340000,
    stock: 11,
  },
  {
    id: 17,
    image: "https://via.placeholder.com/80",
    name: "Quần jogger",
    type: "Quần",
    size: "L",
    color: "Xám",
    price: 310000,
    stock: 20,
  },
  {
    id: 18,
    image: "https://via.placeholder.com/80",
    name: "Váy maxi",
    type: "Váy",
    size: "M",
    color: "Xanh biển",
    price: 450000,
    stock: 7,
  },
  {
    id: 19,
    image: "https://via.placeholder.com/80",
    name: "Áo khoác bomber",
    type: "Áo",
    size: "L",
    color: "Xanh rêu",
    price: 650000,
    stock: 13,
  },
  {
    id: 20,
    image: "https://via.placeholder.com/80",
    name: "Áo thun basic",
    type: "Áo",
    size: "M",
    color: "Đen",
    price: 200000,
    stock: 26,
  },
  {
    id: 21,
    image: "https://via.placeholder.com/80",
    name: "Quần legging",
    type: "Quần",
    size: "S",
    color: "Đen",
    price: 250000,
    stock: 24,
  },
  {
    id: 22,
    image: "https://via.placeholder.com/80",
    name: "Áo len cổ lọ",
    type: "Áo",
    size: "M",
    color: "Nâu",
    price: 360000,
    stock: 12,
  },
  {
    id: 23,
    image: "https://via.placeholder.com/80",
    name: "Váy ngắn dạ tweed",
    type: "Váy",
    size: "S",
    color: "Hồng nhạt",
    price: 520000,
    stock: 8,
  },
  {
    id: 24,
    image: "https://via.placeholder.com/80",
    name: "Áo sơ mi tay dài",
    type: "Áo",
    size: "L",
    color: "Trắng",
    price: 300000,
    stock: 15,
  },
];